# Generated by Django 4.1.7 on 2023-03-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='file',
            field=models.FileField(default=1, max_length=254, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
